### ISSUE TITLE
Cannot connect to crafty control

### ISSUE THREAD

**Issue by Caelanj** [LetsUpdate/crafty_controller#1]
On the first page, I put in my API key and the IP with the port and it says it can't connect. Tried the computer IP, and my public IP. ![Screenshot_20200903-210030.jpg](https://user-images.githubusercontent.com/37782194/92107089-9094e100-ee28-11ea-8636-bdd0e2ebf543.jpg)

**Comment by Caelanj** [comment]
Turned out my API key was wrong 😕

**Comment by LetsUpdate** [comment]
If the new API comes out i will try to fix these bugs, and rewrite the core request system, and make it more reliable :)

**Comment by Rowdyboy02** [comment]
I have the same problem. Though I am 95% sure my API key is correct because I copy and pasted it from the panel config itself... Is there anything I could be doing wrong? I have https://xx.xxx.xx.xx:8000 as the IP and like I said C/P the API... So I'm lost

**Comment by LetsUpdate** [comment]
Try without the https://
So x.x.x.x:yyyy

**Comment by Rowdyboy02** [comment]
> Try without the https://
> So x.x.x.x:yyyy

This worked! Thank you 😁

**Comment by LukasDoesDev** [comment]
I suggest this issue be closed as the problem is resolved.
